name: 'Create deployment information'
description: 'Creates the deploymentInfo.json file'
inputs:
  archive-path:
    description: 'the directory where the json file is located'
    required: true
    default: './'
outputs:
  cf-manifest-path:
    description: 'The path to the manifest file required to deploy to cloudfoundry'
  artifact-path:
    description: 'The path to the archive to deploy'
runs:
  using: 'node12'
  main: 'dist/index.js'
