name: 'Create deployment information'
description: 'Creates the deploymentInfo.json file'
inputs:
  artifact-base-name:
    description: 'The artifact base name without version'
    required: true
  artifact-version:
    description: 'The artifact version'
    required: true
  archive-name:
    description: 'The archive name'
    required: true
    default: './'
  target-path:
    description: 'The directory where the json file is created'
    required: true
    default: './build/libs'
  target-filename:
    description: 'The filename of the created json file'
    default: 'deploymentInfo.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
